Disable UCL

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -44,43 +44,45 @@ else
 	make_define 'kqueue_DEPENDS' ''	
 fi
 
-check_header 'ucl.h'
-if [ $check_header_ucl_h -eq 0 ] ; then
-	echo "building a local copy of libucl.. "
-
-	# KLUDGE: OpenBSD does not support -gstrict-dwarf
-	if [ `uname` = 'OpenBSD' ] ; then
-		dwarf_options="-gdwarf-2"
-	else
-		dwarf_options="-gdwarf-2 -gstrict-dwarf"
-	fi
-
-	ucldir="$TOPDIR/vendor/libucl-0.8.0"
-	make_define 'libucl_dir' "$ucldir"
-	make_define 'libucl_CFLAGS' "-I$libucl_dir/include"
-	make_define 'libucl_LDFLAGS' ""
-	make_define 'libucl_LDADD' "$libucl_dir/src/.libs/libucl.a"
-	make_define 'libucl_DEPENDS' "$libucl_dir/src/.libs/libucl.a"
-	tar -C $TOPDIR/vendor -zxf $TOPDIR/vendor/libucl-0.8.0.tar.gz
-	_savedir=`pwd`
-	set -x
-	cd $ucldir
-	test -e configure || autoreconf -fvi || err 'autogen failed'
-	test -e install-sh || libtoolize --force
-	test -e Makefile || CFLAGS="$dwarf_options -g -O2 -fPIC" ./configure || err 'configure failed'
-	set +x
-	cd $_savedir
-
-	custom_target "$libucl_dir/src/.libs/libucl.a" " " \
-		"cd $libucl_dir && make"
-
-else
-	# KLUDGE: assumes libucl is installed in /usr/local, like on FreeBSD
-	make_define 'libucl_CFLAGS' '-I /usr/local/include'
-	make_define 'libucl_LDFLAGS' '-L /usr/local/lib'
-	make_define 'libucl_LDADD' '-lucl'
-	make_define 'libucl_DEPENDS' ''	
-fi
+# DEADWOOD: remove ucl from this project
+#
+#check_header 'ucl.h'
+#if [ $check_header_ucl_h -eq 0 ] ; then
+#	echo "building a local copy of libucl.. "
+#
+#	# KLUDGE: OpenBSD does not support -gstrict-dwarf
+#	if [ `uname` = 'OpenBSD' ] ; then
+#		dwarf_options="-gdwarf-2"
+#	else
+#		dwarf_options="-gdwarf-2 -gstrict-dwarf"
+#	fi
+#
+#	ucldir="$TOPDIR/vendor/libucl-0.8.0"
+#	make_define 'libucl_dir' "$ucldir"
+#	make_define 'libucl_CFLAGS' "-I$libucl_dir/include"
+#	make_define 'libucl_LDFLAGS' ""
+#	make_define 'libucl_LDADD' "$libucl_dir/src/.libs/libucl.a"
+#	make_define 'libucl_DEPENDS' "$libucl_dir/src/.libs/libucl.a"
+#	tar -C $TOPDIR/vendor -zxf $TOPDIR/vendor/libucl-0.8.0.tar.gz
+#	_savedir=`pwd`
+#	set -x
+#	cd $ucldir
+#	test -e configure || autoreconf -fvi || err 'autogen failed'
+#	test -e install-sh || libtoolize --force
+#	test -e Makefile || CFLAGS="$dwarf_options -g -O2 -fPIC" ./configure || err 'configure failed'
+#	set +x
+#	cd $_savedir
+#
+#	custom_target "$libucl_dir/src/.libs/libucl.a" " " \
+#		"cd $libucl_dir && make"
+#
+#else
+#	# KLUDGE: assumes libucl is installed in /usr/local, like on FreeBSD
+#	make_define 'libucl_CFLAGS' '-I /usr/local/include'
+#	make_define 'libucl_LDFLAGS' '-L /usr/local/lib'
+#	make_define 'libucl_LDADD' '-lucl'
+#	make_define 'libucl_DEPENDS' ''	
+#fi
 
 make_define VENDOR_CXXFLAGS "-I${TOPDIR}/vendor $libucl_CFLAGS $kqueue_CFLAGS"
 make_define VENDOR_LDFLAGS "$libucl_LDFLAGS $kqueue_LDFLAGS"
